openapi: 3.0.1
info:
  title: Core Banking System Core Connector Send Money API
  description: >
    Specification for Core Banking System Core Connectors Send Money API.

    This API is intended to be implemented by the Core Connector. It is used to 
    initiate transfers from a DFSP Operations application.


    **USE CASE AND SCENARIO**


    Assuming a customer in your DFSP wants to send money from their account held
    in your bank to another customer whose account is in another bank in the Mojaloop
    Scheme.
    Once the customer has initaited the transfer using your application, to effect the transfer,
    a POST send-money api call will be sent through this api. This api is to be implemented by the 
    core connector such that is then effectively communicates with  the DFSP Hosted Mojaloop
    connector to be able to effect the transfer.


    **Note on terminology:** The term "Switch" is equal to the term "Hub", and
    the term "FSP" is equal to the term "DFSP".
  license:
    name: Apache License Version 2.0, January 2004
    url: https://github.com/mojaloop/documentation/blob/main/LICENSE.md
  version: 2.1.0
paths:
  /:
    get:
      summary: Health check endpoint
      description: >-
        This endpoint allows a user of the SDK scheme adapter to check the
        outbound transfers service is listening.
      tags:
        - Health
      responses:
        '200':
          description: >-
            Returns empty body if the scheme adapter outbound transfers service
            is running.
  /send-money:
    post:
      summary: Send Money endpoint 
      description: >- 
        The Endpoint used by the DFSP Operations application to initiate send money 
        requests to the mojaloop connector
      tags:
        - Send Money  
      responses:
        '200':
          description: >-
            Response for send money request. A quote if it is double 
            integration or a payment status response if it is single
            integration
